### ISSUE TITLE
CA expired

### ISSUE THREAD

**Issue by piktaszuikis** [Kagami/nacl_sdk#1]
Looks like old *.storage.googleapis.com certificate expired at 2018-10-30.
Tried to add the new one, but my hands must be crooked and it doesn't work.
Please show me the way, sensei!

**Comment by Kagami** [comment]
What commands fails for you? I can see it changed but downloading pepper works fine.
Anyway, try [this one](https://github.com/Kagami/nacl_sdk/blob/12f20c69a66c5d1e91b9b91b6d1a1b52ac676274/sdk_tools/cacerts.txt).

**Comment by piktaszuikis** [comment]
`./naclsdk update` on a fresh repo is what fails me:

```git clone https://github.com/Kagami/nacl_sdk.git
cd nacl_sdk/
git checkout update-certs
ln -s /usr/bin/python2 ./python
export PATH="$(pwd):$PATH" #hax for python2
./naclsdk update
```
```
Traceback (most recent call last):
  File "/home/temptation1/nacl_sdk/sdk_tools/sdk_update_main.py", line 436, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/temptation1/nacl_sdk/sdk_tools/sdk_update_main.py", line 427, in main
    return cmd(parser, argv[1:])
  File "/home/temptation1/nacl_sdk/sdk_tools/sdk_update_main.py", line 225, in CMDupdate
    options = parser.parse_args(args)
  File "/home/temptation1/nacl_sdk/sdk_tools/sdk_update_main.py", line 416, in Parse
    UpdateSDKTools(options, args)
  File "/home/temptation1/nacl_sdk/sdk_tools/sdk_update_main.py", line 363, in UpdateSDKTools
    remote_manifest = LoadCombinedRemoteManifest(options.manifest_url, cfg)
  File "/home/temptation1/nacl_sdk/sdk_tools/sdk_update_main.py", line 164, in LoadCombinedRemoteManifest
    manifest = LoadRemoteManifest(default_manifest_url)
  File "/home/temptation1/nacl_sdk/sdk_tools/sdk_update_main.py", line 146, in LoadRemoteManifest
    url_stream = download.UrlOpen(url)
  File "/home/temptation1/nacl_sdk/sdk_tools/download.py", line 25, in UrlOpen
    return url_opener.open(request)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/home/temptation1/nacl_sdk/sdk_tools/third_party/fancy_urllib/__init__.py", line 414, in do_open
    url_error.reason.args[1])
third_party.fancy_urllib.InvalidCertificateException: Host storage.googleapis.com returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)):
To learn more, see http://code.google.com/appengine/kb/general.html#rpcssl
Traceback (most recent call last):
  File "/home/temptation1/nacl_sdk/sdk_tools/sdk_update_main.py", line 436, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/temptation1/nacl_sdk/sdk_tools/sdk_update_main.py", line 427, in main
    return cmd(parser, argv[1:])
  File "/home/temptation1/nacl_sdk/sdk_tools/sdk_update_main.py", line 228, in CMDupdate
    remote_manifest = LoadCombinedRemoteManifest(options.manifest_url, cfg)
  File "/home/temptation1/nacl_sdk/sdk_tools/sdk_update_main.py", line 164, in LoadCombinedRemoteManifest
    manifest = LoadRemoteManifest(default_manifest_url)
  File "/home/temptation1/nacl_sdk/sdk_tools/sdk_update_main.py", line 146, in LoadRemoteManifest
    url_stream = download.UrlOpen(url)
  File "/home/temptation1/nacl_sdk/sdk_tools/download.py", line 25, in UrlOpen
    return url_opener.open(request)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/home/temptation1/nacl_sdk/sdk_tools/third_party/fancy_urllib/__init__.py", line 414, in do_open
    url_error.reason.args[1])
third_party.fancy_urllib.InvalidCertificateException: Host storage.googleapis.com returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)):
To learn more, see http://code.google.com/appengine/kb/general.html#rpcssl
```

Commenting out `request.set_ssl_info(ca_certs=ca_certs)` in download.py solves the problem, but I don't think that is the right solution.
I will check this on another machine in the evening.

**Comment by Kagami** [comment]
What certs does `openssl s_client -showcerts -connect storage.googleapis.com:443` print for you?

**Comment by piktaszuikis** [comment]
`openssl s_client -showcerts -connect storage.googleapis.com:443` returns
```
-----BEGIN CERTIFICATE-----
MIIGajCCBVKgAwIBAgIINpx2PQ67WTwwDQYJKoZIhvcNAQELBQAwVDELMAkGA1UE
BhMCVVMxHjAcBgNVBAoTFUdvb2dsZSBUcnVzdCBTZXJ2aWNlczElMCMGA1UEAxMc
R29vZ2xlIEludGVybmV0IEF1dGhvcml0eSBHMzAeFw0xODExMDcwODU5MDBaFw0x
OTAxMzAwODU5MDBaMHIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlh
MRYwFAYDVQQHDA1Nb3VudGFpbiBWaWV3MRMwEQYDVQQKDApHb29nbGUgTExDMSEw
HwYDVQQDDBgqLnN0b3JhZ2UuZ29vZ2xlYXBpcy5jb20wggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQDrZv9NyEvKNvwykrrm/u72LGZbNsJiDdTu+LYAwavB
uN+Y9qoBOahU14IWISdmq4Y048FGTUFKLYnIKw9paJJ85qakusWu7HHAyGmz8hb/
LVPEVC7htXOHJUBr1cOKCNYB5Yr7cQFHGYX65d2iRNWtiOS/ldlezJaqJLJl+NLF
qqUwseOO1pXXjHuwSsRTOPnJ7+EaqEZ5o2x4sPXIwQ3UsvwA9DWpWdqAP9bL582T
0xh1qZjggDbxrnZ8gdNIjQAOCycNWLPHFfVYXcLC/WZCDgP8nfBm5CbKzZE6PlQ6
zGeDKDwAlfoBhVw1a63IJ80ao5VtXcvx+nlZutXzyqm/AgMBAAGjggMgMIIDHDAT
BgNVHSUEDDAKBggrBgEFBQcDATCCAfUGA1UdEQSCAewwggHoghgqLnN0b3JhZ2Uu
Z29vZ2xlYXBpcy5jb22CJCouYXBwc3BvdC5jb20uc3RvcmFnZS5nb29nbGVhcGlz
LmNvbYIiKi5jb21tb25kYXRhc3RvcmFnZS5nb29nbGVhcGlzLmNvbYIpKi5jb250
ZW50LXN0b3JhZ2UtZG93bmxvYWQuZ29vZ2xlYXBpcy5jb22CJyouY29udGVudC1z
dG9yYWdlLXVwbG9hZC5nb29nbGVhcGlzLmNvbYIgKi5jb250ZW50LXN0b3JhZ2Uu
Z29vZ2xlYXBpcy5jb22CECouZ29vZ2xlYXBpcy5jb22CISouc3RvcmFnZS1kb3du
bG9hZC5nb29nbGVhcGlzLmNvbYIfKi5zdG9yYWdlLXVwbG9hZC5nb29nbGVhcGlz
LmNvbYIfKi5zdG9yYWdlLnNlbGVjdC5nb29nbGVhcGlzLmNvbYIgY29tbW9uZGF0
YXN0b3JhZ2UuZ29vZ2xlYXBpcy5jb22CK3N0YXRpYy5wYW5vcmFtaW8uY29tLnN0
b3JhZ2UuZ29vZ2xlYXBpcy5jb22CFnN0b3JhZ2UuZ29vZ2xlYXBpcy5jb22CHXN0
b3JhZ2Uuc2VsZWN0Lmdvb2dsZWFwaXMuY29tgg91bmZpbHRlcmVkLm5ld3MwaAYI
KwYBBQUHAQEEXDBaMC0GCCsGAQUFBzAChiFodHRwOi8vcGtpLmdvb2cvZ3NyMi9H
VFNHSUFHMy5jcnQwKQYIKwYBBQUHMAGGHWh0dHA6Ly9vY3NwLnBraS5nb29nL0dU
U0dJQUczMB0GA1UdDgQWBBTd5PibdHDZfuf0hdKCH+Ybutpk9TAMBgNVHRMBAf8E
AjAAMB8GA1UdIwQYMBaAFHfCuFCaZ3Z2sS3ChtCDoH6mfrpLMCEGA1UdIAQaMBgw
DAYKKwYBBAHWeQIFAzAIBgZngQwBAgIwMQYDVR0fBCowKDAmoCSgIoYgaHR0cDov
L2NybC5wa2kuZ29vZy9HVFNHSUFHMy5jcmwwDQYJKoZIhvcNAQELBQADggEBALRh
Ubw1fIjDaYNseFeve+Ia+nhjfs20G9CaK5SnnoAP6IN4+r+XFAw61nq6nS+d18+u
i57WgNviXt9qwQbZvupLVcfFK+afExxSiDpDEw6bD5/llrUjRiJLyDQALn9htjGP
A/ZhZ1kon3EEsbrWRiv0MfeGTppprs5Hu9T6KOWqsZrjHWags2y2SgGJlbJGVlp0
qBBesNPYzPaXD3ZYgj9kQxkN5yfaoOnUaTUJvCk5zCx89RpxASHES/9TmpNCRJLX
gcAc8Ch1wOtlmzEY8T70d+uRTKgeOHMLt0SW56sfynujOLd95qUwbSlSYFJcXNAC
0BfZ4XJBDhC6hsUyFTc=
-----END CERTIFICATE-----
```

and `openssl s_client -showcerts -servername storage.googleapis.com -connect storage.googleapis.com:443` returns
```
-----BEGIN CERTIFICATE-----
MIIGajCCBVKgAwIBAgIIUc1SNVc9asAwDQYJKoZIhvcNAQELBQAwVDELMAkGA1UE
BhMCVVMxHjAcBgNVBAoTFUdvb2dsZSBUcnVzdCBTZXJ2aWNlczElMCMGA1UEAxMc
R29vZ2xlIEludGVybmV0IEF1dGhvcml0eSBHMzAeFw0xODEwMzAxMzE0MThaFw0x
OTAxMjIxMzE0MDBaMHIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlh
MRYwFAYDVQQHDA1Nb3VudGFpbiBWaWV3MRMwEQYDVQQKDApHb29nbGUgTExDMSEw
HwYDVQQDDBgqLnN0b3JhZ2UuZ29vZ2xlYXBpcy5jb20wggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQDXxcbjwFbgkZDlk5EBhGPhlIuV5esNdRSu8Z3rOR1b
PqsNcRmie+8EoelFHj1vObWcCZN2qrO6vWqvlp663HY5BTqXZjR6wWjmKScBAOJU
vjEKmbeBg84y9oc/stK7/XzWshrq0i3y52WedhiuPuFi1M1bY2E9Pvxot838zV0N
YWCgHJzRUVOxkutHKeZuIS7Ql34QmI2uyl6f69ENqtUU+LkggJt1mPDAnxgROoAs
8EKgb+cooUFXbK4eHvlx7ceFcjTbpDOipVXUlUY44V9lsOLKIa/CSJlfeu3N1pUj
H8E1m08Cap/Zzu3RW1C2dgueJOiFNqOLOCP3zkgfjHrhAgMBAAGjggMgMIIDHDAT
BgNVHSUEDDAKBggrBgEFBQcDATCCAfUGA1UdEQSCAewwggHoghgqLnN0b3JhZ2Uu
Z29vZ2xlYXBpcy5jb22CJCouYXBwc3BvdC5jb20uc3RvcmFnZS5nb29nbGVhcGlz
LmNvbYIiKi5jb21tb25kYXRhc3RvcmFnZS5nb29nbGVhcGlzLmNvbYIpKi5jb250
ZW50LXN0b3JhZ2UtZG93bmxvYWQuZ29vZ2xlYXBpcy5jb22CJyouY29udGVudC1z
dG9yYWdlLXVwbG9hZC5nb29nbGVhcGlzLmNvbYIgKi5jb250ZW50LXN0b3JhZ2Uu
Z29vZ2xlYXBpcy5jb22CECouZ29vZ2xlYXBpcy5jb22CISouc3RvcmFnZS1kb3du
bG9hZC5nb29nbGVhcGlzLmNvbYIfKi5zdG9yYWdlLXVwbG9hZC5nb29nbGVhcGlz
LmNvbYIfKi5zdG9yYWdlLnNlbGVjdC5nb29nbGVhcGlzLmNvbYIgY29tbW9uZGF0
YXN0b3JhZ2UuZ29vZ2xlYXBpcy5jb22CK3N0YXRpYy5wYW5vcmFtaW8uY29tLnN0
b3JhZ2UuZ29vZ2xlYXBpcy5jb22CFnN0b3JhZ2UuZ29vZ2xlYXBpcy5jb22CHXN0
b3JhZ2Uuc2VsZWN0Lmdvb2dsZWFwaXMuY29tgg91bmZpbHRlcmVkLm5ld3MwaAYI
KwYBBQUHAQEEXDBaMC0GCCsGAQUFBzAChiFodHRwOi8vcGtpLmdvb2cvZ3NyMi9H
VFNHSUFHMy5jcnQwKQYIKwYBBQUHMAGGHWh0dHA6Ly9vY3NwLnBraS5nb29nL0dU
U0dJQUczMB0GA1UdDgQWBBTgIxJAxxt6ucJKvDzXWshGh4goKDAMBgNVHRMBAf8E
AjAAMB8GA1UdIwQYMBaAFHfCuFCaZ3Z2sS3ChtCDoH6mfrpLMCEGA1UdIAQaMBgw
DAYKKwYBBAHWeQIFAzAIBgZngQwBAgIwMQYDVR0fBCowKDAmoCSgIoYgaHR0cDov
L2NybC5wa2kuZ29vZy9HVFNHSUFHMy5jcmwwDQYJKoZIhvcNAQELBQADggEBAEgU
u73dtgFdsLPcGWvgeRIrbHTKnyEqCzWAYXLIea53Z4SterIEH3x1yIsDjo+sst9Q
6dFaGx+xXwO/DUKjIeRKwVsKGG1JDceBHrerIX88p54H10O6IjRFFE3nxSwdYnyG
hudqpgMlT/UOY5l55mONWv9Y+y4YU4HJx1Q+eRI8HsPyOJHkK5oaZaLEkc81Majp
QbEQxOVTMf0OW0HfKPfyvi72pw223GVLe34piCH3jp92X6iSgXiXhEj+FxvzevO/
8lDiUYMvdViju9tvZFqYbn3DjXGjDraZ0xMNbd5DR3wgKnEhOkqbxFQEUFE6FASN
3aP+6zeDYoMRluWEHg8=
-----END CERTIFICATE-----
```

However the problem is not here. After lots of digging I've discovered, that openssl is the one to blame: version 1.1.0 works fine even with expired certs, but version 1.1.1 rejects all of them. I haven't find out why yet, but with each minute I'm more and more willing to simply comment out CA check all together...

**Comment by Kagami** [comment]
Fixed! Latest OpenSSL requires `server_hostname` option, it always fails with error even when `check_hostname` is not set. Regarding expired certs - only CA cert (third) is actually required, others are returned by the server.
